### ISSUE TITLE
esp-idf update

### ISSUE THREAD

**Issue by ozanoner** [platformio/platformio-libmirror#115] opened 2018-01-23 18:58 UTC
can you update the framework to the latest version, pls? some components are missing (like esp_bt.h) regards..
[https://github.com/espressif/esp-idf/](https://github.com/espressif/esp-idf/)

**Comment by ivankravets** [comment] 2018-01-24 14:17
Duplicate of https://github.com/platformio/platform-espressif32/issues/66

**Closed by ivankravets** 2018-01-24 14:17 UTC
